### PR TITLE
remove relative test paths

### PR DESCRIPTION
**Pull request by rabeckett**
The tests are currently manually searching for the path to the test files. However, this breaks easily. For example, if the project folder is not called "groot" then all the tests will fail.

I added a TestFiles directory in the test project with all the relevant files and forced Visual Studio to copy these files to the exe output directory after every build.

It may be the case that this copy will need to added to CMake as well for Linux, but I don't have a way to test that.

### CODE REVIEW

**Comment by SivaKesava1** [comment]
To make it work for Linux, we have to copy the Testfiles directory to the build directory but to copy that we will make the assumption there will be a "test" directory similar to the way we assume "groot" folder exists. 
I have named them libgroot to be consistent with the Linux. Is groot_lib the MS style?

**Comment by rabeckett** [comment]
The difference is that we control the name of the "test" and  "TestFiles" directories since it is part of the project. Whereas we don't control the name of the project directory. The tests were failing for me because I had renamed to project folder. It is also brittle right now; if I have groot/groot/test/... and the outer groot/ has a test directory, then it will fail.

For libgroot, it is just renaming the name in visual studio to what I've seen before, but not the folder. I can change it back if you want.

**Comment by SivaKesava1** [comment]
Got it. I think you forgot to add the demo files under TestFiles folder. I will add them and also update CMakeFile to make it work for Linux and make a commit and then merge it.

**Comment by rabeckett** [comment]
Awesome! I had renamed demo to net.sy since it was replicating the other test files.

**Pull request merged**
